inherit_from: .rubocop_todo.yml

Layout/EndOfLine:
  EnforcedStyle: lf

# Due to old Ruby
Layout/IndentHeredoc:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
